### PR TITLE
Refactor and cleanup

### PR DESCRIPTION
**Pull request by alexandrevicenzi**
Black was used to format the code as well some pylint issues where
fixed.

### CODE REVIEW

**Comment by alexandrevicenzi** [comment]
This PR relates to #140.

**Comment by alexandrevicenzi** [comment]
@jantic can you please test this before merging? It should not break anything, but just to be 100% sure.

**Comment by jantic** [comment]
One more thing to note is that ColorizeTrainingVideo.ipynb needs a reference added for this in lieu of the import changes:

from deoldify.augs import *

**Comment by alexandrevicenzi** [comment]
@jantic I'll take a look.

**Comment by alexandrevicenzi** [comment]
@jantic I just reverted all import changes, I'll look into that later, for now I will only format the code.

**Comment by alexandrevicenzi** [comment]
@jantic This patch has only code format now, nothing should break.

**Comment by jantic** [comment]
This looks great!  I went through every single line of code that was changed just to make sure it was just formatting.  Thanks and good call on that.

**Pull request merged**
