### PR TITLE
Added support for resume and lots of other improvements

### PR DESCRIPTION
**Pull request by seidnerj**
1. Initialize global logger with a proper format

2. Bump pytorch to v1.12.0 (from v1.11.0) in order to overcome current dependency incompatibility

3. Lots of styling improvements to make the code more readable (visualize.py & filters.py)

4. Added support for resuming including detection of whether raw frames were already fully extracted (resume is set to True in VideoColorizer notebook example but in general defaults to False)

5. Replace "colorize_from_{url/file_name/path}" with a single "colorize_from_uri" function that detects whether the uri parameter is a URL or not and acts accordingly
 
6. Added logging some messages to indicate progress and output some useful information

7. Updated example in VideoColorizer notebook (note that "watermarked" is now set to False in the example)

### CODE REVIEW

**Comment by seidnerj** [comment]
Can someone please review this? Thx

**Comment by jantic** [comment]
Hey, sorry about not saying this earlier- I'm in the middle of a move and my pc has been packed away for a while. I won't be able to properly review and test this stuff until another month or so. Thanks!

**Comment by seidnerj** [comment]
No worries, just wanted to make sure that this was actually seen by someone. Cheers!

**Comment by robbyt** [comment]
@seidnerj it's a bit difficult to review the changes in this PR because it contains both formatting fixes as well as functional code changes. It would be much easier to review and merge these changes if this large PR was split into several smaller PRs.

**Comment by alexandrevicenzi** [comment]
Too many changes and just 3 commits. Would be nice to split a few things and have at least 7 commits to reflect your changes.

For formatting, you can also use Black and have everything consistent.

**Comment by seidnerj** [comment]
Hey guys, it's been over a month since I worked on this and I have moved on to other things. I understand this is difficult to merge so would understand if you just closed this since its unlikely I'll have time to go back and break this out to separate commits.

**Comment by jantic** [comment]
I finally got settled after the move and can now review these things. Since you won't have the time to do the likely back and forth here, I'll close this. Thanks!

**Pull request closed without merging**
