### PR TITLE
[Docker][CPU][Wrapper] a few wrapper to simplify onboarding including running without

### PR DESCRIPTION
**Pull request by jqueguiner**
Following PR #272 here is the expected behavior.

### CODE REVIEW

**Comment by jqueguiner** [comment]
- quickstart added

```bash
$ ./quick_start.sh
usage : ./quick_start.sh notebook password -- to start the notebook with password
             leave empty for no password (not recommended)
usage : ./quick_start.sh image_api  -- to start image api
usage : ./quick_start.sh video_api  -- to start video api

you can add non mandatory arguments
usage : ./quick_start.sh image_api port host -- for custom port or host
```


- quickstart auto detect the presence of GPU including when running the docker with ipc option as well as in the pytorch implementation.

- Fixed also the download

- made a pseudo local cache management of models

-api_cmd_example added 
```bash
$ api_cmd_example.sh
usage : ./api_cmd_example.sh image  -- to test image api
usage : ./api_cmd_example.sh video  -- to test video api

you can add non mandatory arguments
usage : ./api_cmd_example.sh image port host -- for custom port or host
```

**Comment by jantic** [comment]
Wow, great stuff, thanks @jqueguiner ! I'll wait for @mewbot97 to review.

**Comment by tigran1997** [comment]
Hey @jqueguiner can't we add these steps in Dockerfile-api as well?
`RUN [[ ! -f /data/models/ColorizeArtistic_gen.pth ]] && wget -O /data/models/ColorizeArtistic_gen.pth https://data.deepai.org/deoldify/ColorizeArtistic_gen.pth
RUN [[ ! -f /data/models/ColorizeVideo_gen.pth ]] && wget -O /data/models/ColorizeVideo_gen.pth https://data.deepai.org/deoldify/ColorizeVideo_gen.pth
`

**Review by jantic — APPROVED** [review]
Looks great!  Thanks as always @jqueguiner - very generous of you.

**Pull request merged**
