### PR TITLE
colab notebook updated to work with local Drive images

### PR DESCRIPTION
**Pull request by mariabg**
I added to @mc-robinson 's notebook the option of importing and saving the images from a local Drive folder. I hope that you also find this useful, let me know if I should make any change on my contribution. Cheers!

### CODE REVIEW

**Comment by mariabg** [comment]
You are right, I will restart the kernel and push again. Also, I realised that the ["Open in Colab"](https://github.com/mariabg/DeOldify/blob/colab-working-with-Drive/DeOldify_colab.ipynb) button from Github still links to your notebook, how did you set that?

I didn't know I could pydrive to get/save images, I'll try to implement it that way and upload the new version.

I asked the other day to @jantic for this "results_dir" and he implemented right away, I also think it will help users a lot!

**Comment by mariabg** [comment]
Update! I fixed the "Open in Colab" thingy

**Comment by jantic** [comment]
Going to merge -then- test my attempted PIL fixes....Will just be easier that way!  This PIL stuff is a pain.

**Comment by jantic** [comment]
Phew.... So there was a lingering issue with Pillow versioning there.  I hacked away at it until it finally worked.  Was really quite a confusing issue honestly.  Anyway- it works, I've confirmed!  Really like this- this makes this notebook even more useful and user friendly which I love.  Thank you so much @mariabg  and @mc-robinson!

**Pull request merged**
