### PR TITLE
pypi: rename fasterai to deoldify

### PR DESCRIPTION
**Pull request by alexandrevicenzi**
It will be better to do:

    from deoldify import visualize

Than:

    from fasterai import visualize

The PyPI package will be called DeOldify, in this case
it makes more sense to have an import name that matches
the package name.

Also, fasterai resembles fastai library, and DeOldify
is not a library to use with fastai, it's built on
top of it.

### CODE REVIEW

**Comment by alexandrevicenzi** [comment]
This patch is part of #140.

**Comment by jantic** [comment]
This is great.  Tested and reviewed.  It's a go.  Thanks!

**Comment by jantic** [comment]
Sorry.... Didn't go through proper review process on this one.  Doh!

**Comment by alexandrevicenzi** [comment]
@jantic is there a bug? :thinking:

**Comment by jantic** [comment]
No it's great!  I just didn't put the review comment in the right place.  Did it as a normal comment instead.  "This is great. Tested and reviewed. It's a go. Thanks!"

**Pull request merged**
