### PR TITLE
Dockerfile pip install refactored

### PR DESCRIPTION
**Pull request by macbre**
Install pip dependencies in a single Docker layer

@jantic - did you guys consider moving Python dependencies list into `requirements.txt` file? This way dependabot can be used to make sure that dependencies stay up to date. Unless there's a reason to stick to a specific versions.

### CODE REVIEW

**Comment by alexandrevicenzi** [comment]
There's a requirements.txt already, perhaps the dockerfile could use it.

**Comment by jantic** [comment]
I'll leave this up to @jqueguiner

**Comment by jqueguiner** [comment]
all good to me @jantic

**Review by jantic — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
