### PR TITLE
CPU support for colorization

### LINKED ISSUE #157: Run predict in CPU - Solved
Hi, I've got to run the prediction in CPU I will make a pull request from my fork :)

### PR DESCRIPTION
**Pull request by alexandrevicenzi**
This was based on #168 and fixes #157.

### CODE REVIEW

**Comment by alexandrevicenzi** [comment]
@alejandrods, please take a look.

**Comment by alejandrods** [comment]
I don't understand why you have closed my pull request. Why don't modify my pull request? If you are going to make a new one, my work is lost. I don't understand why are you proceeding on this way. Furthermore, if you make a new pull request, you are the owner of that work, when I have done it.

**Comment by alexandrevicenzi** [comment]
@alejandrods I closed because if you look into this PR there are just 2 lines from your previous PR, everything else is new. It was just easier to start from scratch.

Your work is not lost, what was actually meaningful is here.

About the ownership, you are included in the co-author list, you can check [here](https://github.com/jantic/DeOldify/pull/173/commits/7af71bc5e549fa8d8b659cee2f6c9fa0b694c003).

**Comment by alejandrods** [comment]
I think you completly misunderstand the meaning of Open Source and how to contribute. You are not the best example of reviewer because you delete the pull request in order to do it by yourself, and @jantic, as owner, would have to check that.

**Comment by alexandrevicenzi** [comment]
@alejandrods I believe you don't understand. What part of co-author you don't understand?

You made some contributions, I made as well, we are both owners of this patch/commit, does it matter who opens the pull request? Your name will be in the contributor's list of this project, your name will be in the commit, what else do you want?

I believe that if you can't do what we were asking, why can't we do it by ourselves?
I gave proper credit to you, so stop with this attitude that I don't understand about open source.

Quite frankly, we could have closed your PR without even considering merging it and we can still give up on this CPU idea as it can be a little bit misleading about expectations of what kind of hardware you need to run DeOldify.

**Comment by jantic** [comment]
Fair warning:  I'm going to be blunt.

I stand in firm agreement with @alexandrevicenzi here. Let me be brutally honest:  The code in the pull request just didn't work for us. We kept giving feedback on this and were taking extra time to walk you through this, even though it was something that we could have just took over and done ourselves. Alexandre bent over backwards to accommodate this.  Believe it or not I'm not paying him.  He's awesome and quite frankly he should be paid.

But what wound up ultimately happening here is that Alexandre did what was practical because despite the feedback, the resulting changes weren't sufficient.  From my perspective some of the feedback was simply ignored. We only have so much time in a day.  I know he's working at a full time job and has a lot going on.  Me- I'm working on commercializing DeOldify.  So we simply can't afford to spend a lot of time on a back and forth that just seems counter-productive.

Remember too- this is all getting broadcast in peoples' inboxes.  It doesn't look great from my perspective, I can tell you that much. It's a bit whiny and petty, honestly.  I'd just take the feedback and try to correct course with that for next time.

**Comment by alejandrods** [comment]
Ok! I understand your points! So, apologise for that misunderstanding.

**Comment by flip111** [comment]
I like to try this. Shall i clone it and run with this patch? Or better to wait? Would be nice if the patch includes some documentation what in the configuration needs to change to run in CPU mode.

**Comment by jantic** [comment]
> I like to try this. Shall i clone it and run with this patch? Or better to wait? Would be nice if the patch includes some documentation what in the configuration needs to change to run in CPU mode.

I mean you can certainly try.  It could work just fine for you if you have just one GPU.  It'll be a bit more of a wait until the patch gets fixed.

**Comment by flip111** [comment]
I don't understand from the previous messages if there was still anyone who wants to fix the patch.

@jantic i don't understand your comment about having just one GPU, isn't that the normal situation for most people? My GPU only has 3GB of memory though, so i like to try it with the CPU

**Comment by jantic** [comment]
@flip111 I think I might have misread what you asked.  Yeah go ahead and just try it on the cpu.  It could probably work. 

As far as when this pull request will be merged in- I'm not working on this anytime soon. I can't speak for anybody else.  I'm too heavily involved in other stuff right now.

**Comment by alexandrevicenzi** [comment]
I'll have time to fix it after all these holidays, cheers.

**Comment by jantic** [comment]
I've made the necessary final changes in a separate push, incorporating the changes here.  Thanks guys!

**Comment by flip111** [comment]
https://github.com/jantic/DeOldify/commit/e55c1abc86475a9a840ae2868a473e6e9779a393

**Pull request closed without merging**
